name: tech-stack

on:
  push:
    branches:
      - main

jobs:
  profile_stack_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleich/profile_stack@master
